name: Data Collection

on:
  push:
    branches:
      - i200603  

jobs:
  data-collection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Configurations
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dvc
        pip install dvc-gdrive
        pip install pandas
        pip install numpy

    - name: Initialize DVC
      run: |
        if [ ! -d ".dvc" ]; then
          dvc init
        fi

    - name: Run Data Collection
      run: python src/random_data.py

    - name: Commit Changes
      run: |
        dvc add dummy_sensor_data.csv
        git add dummy_sensor_data.csv.dvc
        git commit -m "Adding Data"
        git push origin i200603

    - name: Authenticate DVC with Google Drive
      run: |
        dvc remote add --default drive gdrive://1wG7W8Dgf9AP26zZWKyEl285Oz-icTH1e
        dvc remote modify drive gdrive_acknowledge_abuse true

    - name: Push Data with DVC
      run: |
        dvc push

    - name: Commit and Push DVC Changes
      run: |
        git add .dvc/config
        git commit -m "Adding data to remote"
        git push origin i200603